name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - rosdistro: humble
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
          # # Jazzy Jalisco (May 2024 - May 2029)
          - rosdistro: jazzy
            docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
    env:
      ROS_DISTRO: ${{ matrix.rosdistro }}
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Install node to Ubuntu (workaround for act)
        if: ${{ env.ACT }}
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash && apt install -y nodejs
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: workaround for jammy
        if: ${{ matrix.rosdistro == 'humble' }}
        run: |
          apt remove libunwind-14-dev -y
          apt install python3-nose -y
          pip uninstall nose -y
      - name: install ccache
        run: |
          apt install -y ccache
      - name: Make ccache dir
        run: |
          mkdir -p /tmp/ccache
      - uses: actions/cache@v3
        with:
          path: /tmp/ccache
          key: ccache-${{ matrix.rosdistro }}
      - name: Install Protocol Buffer
        run: |
          git clone https://github.com/abseil/abseil-cpp.git /abseil-cpp && cd /abseil-cpp
          cmake -S . -B build  -DCMAKE_INSTALL_PREFIX=/usr/local -DABSL_ENABLE_INSTALL=ON  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build --target install --parallel 20
          git clone -b v31.1 https://github.com/protocolbuffers/protobuf.git /protobuf && cd /protobuf
          git submodule update --init --recursive
          cmake -S . -B build   -DCMAKE_INSTALL_PREFIX=/usr/local   -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build --parallel 20 && cmake --install build
          sudo apt update && sudo apt install -y python3-venv python3-pip
          python3 -m venv /.venv --system-site-packages
          echo "PATH=/.venv/bin:${PATH}" >> $GITHUB_ENV
          /.venv/bin/python3 -m pip install protobuf grpcio-tools
      - name: Check protoc
        run: |
          protoc --version
      - name: Search packages in this repository
        id: list_packages
        run: |
          echo name=package_list::$(colcon list --names-only | sed -e ':loop; N; $!b loop; s/\n/ /g') >> "$GITHUB_OUTPUT"
      - name: Show target packages
        run: |
          echo "Target packages: ${{ steps.list_packages.outputs.package_list }}"
      - name: Check dependency-${{ matrix.rosdistro }}.repos existence
        id: check_rosdistro_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency-${{ matrix.rosdistro }}.repos
          allow_failure: false
      - name: Check dependency.repos existence
        id: check_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency.repos
          allow_failure: false
      - name: Run build test with dependency-${{ matrix.rosdistro }}.repos
        uses: ros-tooling/action-ros-ci@v0.3
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'true'
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.rosdistro }}
          vcs-repo-file-url: dependency-${{ matrix.rosdistro }}.repos
          extra-cmake-args: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          rosdep-skip-keys: protobuf-dev protobuf python3-protobuf
        env:
          CCACHE_DIR: /tmp/ccache
          DEVELOP: true
      - name: Run build test with dependency.repos
        uses: ros-tooling/action-ros-ci@v0.3
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'true'
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.rosdistro }}
          vcs-repo-file-url: dependency.repos
          extra-cmake-args: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          rosdep-skip-keys: protobuf-dev protobuf python3-protobuf
        env:
          CCACHE_DIR: /tmp/ccache
          DEVELOP: true
      - name: Run build test without .repos file
        uses: ros-tooling/action-ros-ci@v0.3
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'false'
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.rosdistro }}
          extra-cmake-args: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          rosdep-skip-keys: protobuf-dev protobuf python3-protobuf
        env:
          CCACHE_DIR: /tmp/ccache
          DEVELOP: true
      - name: Notify Slack
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  merge:
    name: merge
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    needs: build
    steps:
      - name: merge PR
        if: ${{ (github.event_name == 'pull_request') && (github.actor == 'wam-v-tan') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.html_url }} --merge
